/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const ContactsIndexLazyImport = createFileRoute('/contacts/')()
const ContactsCreateLazyImport = createFileRoute('/contacts/create')()
const ContactsContactUuidIndexLazyImport = createFileRoute(
  '/contacts/$contactUuid/',
)()
const ContactsContactUuidEditLazyImport = createFileRoute(
  '/contacts/$contactUuid/edit',
)()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ContactsIndexLazyRoute = ContactsIndexLazyImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/contacts/index.lazy').then((d) => d.Route),
)

const ContactsCreateLazyRoute = ContactsCreateLazyImport.update({
  id: '/contacts/create',
  path: '/contacts/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/contacts/create.lazy').then((d) => d.Route),
)

const ContactsContactUuidIndexLazyRoute =
  ContactsContactUuidIndexLazyImport.update({
    id: '/contacts/$contactUuid/',
    path: '/contacts/$contactUuid/',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/contacts/$contactUuid/index.lazy').then((d) => d.Route),
  )

const ContactsContactUuidEditLazyRoute =
  ContactsContactUuidEditLazyImport.update({
    id: '/contacts/$contactUuid/edit',
    path: '/contacts/$contactUuid/edit',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/contacts/$contactUuid/edit.lazy').then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/contacts/create': {
      id: '/contacts/create'
      path: '/contacts/create'
      fullPath: '/contacts/create'
      preLoaderRoute: typeof ContactsCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/contacts/': {
      id: '/contacts/'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/contacts/$contactUuid/edit': {
      id: '/contacts/$contactUuid/edit'
      path: '/contacts/$contactUuid/edit'
      fullPath: '/contacts/$contactUuid/edit'
      preLoaderRoute: typeof ContactsContactUuidEditLazyImport
      parentRoute: typeof rootRoute
    }
    '/contacts/$contactUuid/': {
      id: '/contacts/$contactUuid/'
      path: '/contacts/$contactUuid'
      fullPath: '/contacts/$contactUuid'
      preLoaderRoute: typeof ContactsContactUuidIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/contacts/create': typeof ContactsCreateLazyRoute
  '/contacts': typeof ContactsIndexLazyRoute
  '/contacts/$contactUuid/edit': typeof ContactsContactUuidEditLazyRoute
  '/contacts/$contactUuid': typeof ContactsContactUuidIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/contacts/create': typeof ContactsCreateLazyRoute
  '/contacts': typeof ContactsIndexLazyRoute
  '/contacts/$contactUuid/edit': typeof ContactsContactUuidEditLazyRoute
  '/contacts/$contactUuid': typeof ContactsContactUuidIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/contacts/create': typeof ContactsCreateLazyRoute
  '/contacts/': typeof ContactsIndexLazyRoute
  '/contacts/$contactUuid/edit': typeof ContactsContactUuidEditLazyRoute
  '/contacts/$contactUuid/': typeof ContactsContactUuidIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacts/create'
    | '/contacts'
    | '/contacts/$contactUuid/edit'
    | '/contacts/$contactUuid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacts/create'
    | '/contacts'
    | '/contacts/$contactUuid/edit'
    | '/contacts/$contactUuid'
  id:
    | '__root__'
    | '/'
    | '/contacts/create'
    | '/contacts/'
    | '/contacts/$contactUuid/edit'
    | '/contacts/$contactUuid/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ContactsCreateLazyRoute: typeof ContactsCreateLazyRoute
  ContactsIndexLazyRoute: typeof ContactsIndexLazyRoute
  ContactsContactUuidEditLazyRoute: typeof ContactsContactUuidEditLazyRoute
  ContactsContactUuidIndexLazyRoute: typeof ContactsContactUuidIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ContactsCreateLazyRoute: ContactsCreateLazyRoute,
  ContactsIndexLazyRoute: ContactsIndexLazyRoute,
  ContactsContactUuidEditLazyRoute: ContactsContactUuidEditLazyRoute,
  ContactsContactUuidIndexLazyRoute: ContactsContactUuidIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/contacts/create",
        "/contacts/",
        "/contacts/$contactUuid/edit",
        "/contacts/$contactUuid/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/contacts/create": {
      "filePath": "contacts/create.lazy.tsx"
    },
    "/contacts/": {
      "filePath": "contacts/index.lazy.tsx"
    },
    "/contacts/$contactUuid/edit": {
      "filePath": "contacts/$contactUuid/edit.lazy.tsx"
    },
    "/contacts/$contactUuid/": {
      "filePath": "contacts/$contactUuid/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
