/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const ContactsIndexLazyImport = createFileRoute('/contacts/')()
const ContactsCreateLazyImport = createFileRoute('/contacts/create')()
const ContactsContactUuidLazyImport = createFileRoute(
  '/contacts/$contactUuid',
)()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ContactsIndexLazyRoute = ContactsIndexLazyImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/contacts/index.lazy').then((d) => d.Route),
)

const ContactsCreateLazyRoute = ContactsCreateLazyImport.update({
  id: '/contacts/create',
  path: '/contacts/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/contacts/create.lazy').then((d) => d.Route),
)

const ContactsContactUuidLazyRoute = ContactsContactUuidLazyImport.update({
  id: '/contacts/$contactUuid',
  path: '/contacts/$contactUuid',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/contacts/$contactUuid.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/contacts/$contactUuid': {
      id: '/contacts/$contactUuid'
      path: '/contacts/$contactUuid'
      fullPath: '/contacts/$contactUuid'
      preLoaderRoute: typeof ContactsContactUuidLazyImport
      parentRoute: typeof rootRoute
    }
    '/contacts/create': {
      id: '/contacts/create'
      path: '/contacts/create'
      fullPath: '/contacts/create'
      preLoaderRoute: typeof ContactsCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/contacts/': {
      id: '/contacts/'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/contacts/$contactUuid': typeof ContactsContactUuidLazyRoute
  '/contacts/create': typeof ContactsCreateLazyRoute
  '/contacts': typeof ContactsIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/contacts/$contactUuid': typeof ContactsContactUuidLazyRoute
  '/contacts/create': typeof ContactsCreateLazyRoute
  '/contacts': typeof ContactsIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/contacts/$contactUuid': typeof ContactsContactUuidLazyRoute
  '/contacts/create': typeof ContactsCreateLazyRoute
  '/contacts/': typeof ContactsIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contacts/$contactUuid' | '/contacts/create' | '/contacts'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contacts/$contactUuid' | '/contacts/create' | '/contacts'
  id:
    | '__root__'
    | '/'
    | '/contacts/$contactUuid'
    | '/contacts/create'
    | '/contacts/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ContactsContactUuidLazyRoute: typeof ContactsContactUuidLazyRoute
  ContactsCreateLazyRoute: typeof ContactsCreateLazyRoute
  ContactsIndexLazyRoute: typeof ContactsIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ContactsContactUuidLazyRoute: ContactsContactUuidLazyRoute,
  ContactsCreateLazyRoute: ContactsCreateLazyRoute,
  ContactsIndexLazyRoute: ContactsIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/contacts/$contactUuid",
        "/contacts/create",
        "/contacts/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/contacts/$contactUuid": {
      "filePath": "contacts/$contactUuid.lazy.tsx"
    },
    "/contacts/create": {
      "filePath": "contacts/create.lazy.tsx"
    },
    "/contacts/": {
      "filePath": "contacts/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
